name: Tailwings

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.3

      - run: flyctl secrets set --stage TAILSCALE_AUTHKEY=${{ secrets.TAILSCALE_AUTHKEY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
