# yamllint disable rule:document-start
# https://docs.github.com/actions

name: Lint

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: LeoColomb/.github/.github/workflows/lint.yml@main
